### ISSUE TITLE
Replace com.nhaarman.mockitokotlin2 dependency with org.mockito.kotlin

### ISSUE THREAD

**Issue by yunyeng** [world-federation-of-advertisers/panel-exchange-client#8]
Update WORKSPACE to replace;
"com.nhaarman.mockitokotlin2:mockito-kotlin": "2.2.0" with;
"org.mockito.kotlin:mockito-kotlin": "3.1.0"

**Comment by efoxepstein** [comment]
Once https://github.com/world-federation-of-advertisers/common-jvm/pull/4 lands, this can be done.

**Comment by jonmolle** [comment]
This was fixed with #43 , which migrated to using the common-jvm repo that already replaced that dependency
